### ISSUE TITLE
Have you seen vue-inject

### ISSUE THREAD

**Issue by MVSICA-FICTA** [dealloc/vuec#4]
Ready like DI and its great that it has arrived for Vue, have you seen https://www.npmjs.com/package/vue-inject ? It would be great to build one unfragmented solution!

**Comment by defnorep** [comment]
That project looks much more complex than Vuec. You have to register your dependency in its containing file with the injector, so all of our dependencies are aware that they are being injected. Much more opinionated about how you structure your application.

Vue-Inject seems to be sufficiently different from Vuec to warrant there being two different options!

**Comment by MVSICA-FICTA** [comment]
Just wanted to point it out :) I find myself thinking a lot about structure and scaling these days so having some constraints and the right opinionated approach is something I embrace.

**Comment by dealloc** [comment]
The author of vue-inject seems to have taken a slightly different approach to injecting the dependencies, rather than intercepting the lifecycle hooks as vuec does, the author chose to inject them on the object and retrieve them from a property.

This is interesting, as this approach would not give problems such as #3 has due name mangling.
It might be interesting to support both choices and update the documentation to inform the user about the pros and cons of each

**Comment by dealloc** [comment]
I have implemented a similiar approach into vuec in the dev branch (you can see it [here](https://github.com/dealloc/vuec/commit/fbecf078312f60597a8ccc427030767ea4aea2b0)) but I'm looking if there isn't an easier way to go about this.

Once the documentation is updated this will be merged into master and released
